widgetTheme=widget-themes/original
primaryColor=#0d518e
secondaryColor=#86C953
labelColor=#ffffff
hideWhenOffline=false
contactMail=divulgacao@colegiosoer.com.br
loadingLabel=Carregando...
loginError=Login error
chatHeader=Chat Online
startInfo=Sinta-se a vontade para começar uma conversa!
widgetWidth=370
widgetHeight=411
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/New Message A.mp3
startLabel=Começar
backLabel=Voltar
initMessageBody=Ola, como posso ajudar?
initMessageAuthor=Operador
chatInputLabel=Escreva sua pergunta.
timeDaysAgo=day(s) ago
timeHoursAgo=hour(s) ago
timeMinutesAgo=minute(s) ago
timeSecondsAgo=second(s) ago
offlineMessage=Operador off-line
toggleSoundLabel=Sound effects
toggleScrollLabel=Auto-scroll
toggleEmoticonsLabel=Emoticons
toggleAutoShowLabel=Auto-show
toggleFullscreenLabel=Toggle fullscreen
endChatLabel=Finalizar chat
endChatConfirmQuestion=Tem certeza?
endChatConfirm=Sim
endChatCancel=Cancelar
contactHeader=Contate nos
contactInfo=Todos os operadores estão off-line. Use o email para perguntar.
contactNameLabel=Seu nome
contactMailLabel=Seu email
contactQuestionLabel=Sua pergunta
contactSendLabel=Enviar
contactSuccessHeader=Mensagem enviada
contactSuccessMessage=Sua pergunta foi enviada. Obrigado!
contactErrorHeader=Erro
contactErrorMessage=Erro ao enviar pergunta.
headerHeight=55
installed=1
